# Generated by Django 5.2.9 on 2025-12-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='position',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
