# Generated by Django 5.2.9 on 2025-12-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('club', 'Club Night'), ('festival', 'Festival'), ('external', 'External Event'), ('other', 'Other')], default='club', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('promoter_name', models.CharField(blank=True, max_length=200)),
                ('promoter_email', models.EmailField(blank=True, max_length=254)),
                ('promoter_phone', models.CharField(blank=True, max_length=20)),
                ('epk_link', models.URLField(blank=True)),
                ('hospitality_rider', models.FileField(blank=True, upload_to='riders/hospitality/')),
                ('technical_rider', models.FileField(blank=True, upload_to='riders/technical/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ManyToManyField(blank=True, related_name='event_team', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventArtwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_artworks/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='events.event')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
