# Generated by Django 5.2.9 on 2025-12-04 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='eventartwork',
            options={},
        ),
        migrations.RemoveField(
            model_name='eventartwork',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventartwork',
            name='title',
            field=models.CharField(default='Placeholder Title', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='epk_link',
            field=models.URLField(blank=True, max_length=500, verbose_name='EPK / Press Kit Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(help_text='e.g., Live Music, Club Night, Private Hire', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='hospitality_rider',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Set to False to hide from public/main calendar view.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, help_text='Select staff members involved in this event.', related_name='scheduled_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='technical_rider',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventartwork',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventartwork',
            name='image',
            field=models.ImageField(help_text='Artwork file for marketing or production.', upload_to='event_artwork/'),
        ),
    ]
