# Generated by Django 5.2.9 on 2025-12-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_options_alter_eventartwork_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='epk_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='EPK / Press Kit Link'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, help_text='e.g., Live Music, Club Night, Private Hire', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='hospitality_rider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes'),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='promoter_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='technical_rider',
            field=models.TextField(blank=True, null=True),
        ),
    ]
