# Generated by Django 5.2.9 on 2025-12-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventcategory_promoter_remove_event_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
