# Generated by Django 5.2.9 on 2025-12-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0002_alter_checklistsession_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemresponse',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20),
        ),
    ]
