# Generated by Django 5.2.9 on 2025-12-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0003_alter_itemresponse_status'),
        ('checklists', '0004_create_user_roles'),
    ]

    operations = [
    ]
