# Generated by Django 5.2.9 on 2025-12-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0005_merge_20251202_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(choices=[('security', 'Security'), ('bar', 'Bar'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
