# Generated by Django 5.2.9 on 2025-12-02 21:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_checklisttemplate_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(choices=[('security', 'Security'), ('bar', 'Bar'), ('management', 'Management')], default='security', max_length=20),
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('operational_date', models.DateField(default=django.utils.timezone.localdate)),
                ('incident_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('persons_involved', models.TextField(blank=True, verbose_name='Names/Descriptions of Persons Involved')),
                ('summary', models.TextField(verbose_name='Detailed Summary of Incident')),
                ('action_taken', models.TextField(verbose_name='Action Taken by Staff')),
                ('is_locked', models.BooleanField(default=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidents_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
