# Generated by Django 5.2.9 on 2025-12-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_alter_checklisttemplate_category_incidentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='type',
            field=models.CharField(choices=[('item', 'Item'), ('heading', 'Heading')], default='item', max_length=10),
        ),
    ]
