# Generated by Django 5.2.9 on 2025-12-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0008_checklistitem_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemresponse',
            unique_together={('item', 'session')},
        ),
    ]
