# Generated by Django 5.2.9 on 2025-12-03 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0010_maintenancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='heading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='checklists.checklistitem'),
        ),
    ]
