# Generated by Django 5.2.9 on 2025-12-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattempt',
            name='renewal_due_date',
        ),
    ]
