# Generated by Django 5.2.9 on 2025-12-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_userattempt_renewal_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='renewal_due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
