# Generated by Django 5.2.9 on 2025-12-05 10:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_userattempt_renewal_due_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('sort_code', models.CharField(max_length=10)),
                ('account_number', models.CharField(max_length=20)),
                ('right_to_work_proof', models.FileField(help_text='Required document upload.', upload_to='compliance/rtw/', verbose_name='Right to Work Proof (Passport/Visa)')),
                ('p45_document', models.FileField(blank=True, null=True, upload_to='compliance/p45/', verbose_name='P45 Document (Optional)')),
                ('is_completed', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_doc', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
